name: Bug report
description: Report incorrect behavior
body:
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: input
    attributes:
      label: Browser or Windows version
